let a = 20;
let b = 10;

console.log(a + b) //Addition..
console.log(a - b) //Subtraction...
console.log(a * b) //Multiplication...
console.log(a / b) //Division...
console.log(a === b) //Equal To Boolean Output... 
console.log(a !== b); //Not Equal To Boolean Output...